### ISSUE TITLE
Add support Captcha resolver with high result

### ISSUE THREAD

**Issue by thorvak** [Mehul343/PokeMeow-Auto-Grind-with-Captcha-Solver#5]
Hello I tried several bot for pokemeow but I have bad result with resolver so I'm banned. Can you add a great captcha resolver with high result please ? Thanks

**Comment by Mehul343** [comment]
> Hello I tried several bot for pokemeow but I have bad result with resolver so I'm banned. Can you add a great captcha resolver with high result please ? Thanks

A good captcha solver is paid so if you want good results you will have to pay real money. Also I did mention in the readme that the accuracy is low and you should keep an eye on it.
