### ISSUE TITLE
Error in exception 

### ISSUE THREAD

**Issue by noeno001** [Mehul343/PokeMeow-Auto-Grind-with-Captcha-Solver#6]
Browser: Firefox
Python: 3.10.0
captcha_solver=False
auto_eggs=True

Hi, sometimes these error show up..

![image](https://user-images.githubusercontent.com/10752303/144016911-e7117fb5-2fea-4389-823e-f0176be3a689.png)

Thanks

**Comment by Mehul343** [comment]
> Browser: Firefox Python: 3.10.0 captcha_solver=False auto_eggs=True
> 
> Hi, sometimes these error show up..
> 
> ![image](https://user-images.githubusercontent.com/10752303/144016911-e7117fb5-2fea-4389-823e-f0176be3a689.png)
> 
> Thanks

This comes up when someone else (not someone you have whitelisted) messages in the channel you are grinding in. Please grind in a private channel or whitelist the users you want to be able to message in the channel you are grinding in.
