### ISSUE TITLE
ERROR USER BALANCE ZERO?

### ISSUE THREAD

**Issue by rasyidabdulhalim** [Mehul343/PokeMeow-Auto-Grind-with-Captcha-Solver#9]
![gambar](https://user-images.githubusercontent.com/43528203/146629013-1a88e017-3aca-4d08-b408-b92db1df8fb9.png)

**Comment by Mehul343** [comment]
If you are using captcha solver please create another account on azcaptcha then use the new token. If you are not using captcha solver please disable it in the config.

**Comment by Mehul343** [comment]
Also this repo won't be maintained now. I have made a new bot which you can use by visiting https://github.com/Mehul343/PokeGrinder. This new bot doesn't have much features right now as I am still developing it.
